DROP TABLE MAKER2, PRODUCT22;
CREATE TABLE MAKER2(MAKER_CODE CHAR(4) PRIMARY KEY, MAKER_NAME VARCHAR(30));
CREATE TABLE PRODUCT22(PRODUCT_CODE CHAR(4) PRIMARY KEY, PRODUCT_NAME VARCHAR(30), MAKER_CODE CHAR(4),
FOREIGN KEY (MAKER_CODE) REFERENCES MAKER2(MAKER_CODE) ON DELETE CASCADE);

INSERT INTO MAKER2 VALUES('M001', '나이키');
INSERT INTO MAKER2 VALUES('M002', '리복');

INSERT INTO PRODUCT22 VALUES('P001', '축구화', 'M001');
INSERT INTO PRODUCT22 VALUES('P002', '러닝화', 'M002');

DELETE FROM MAKER2 WHERE MAKER_CODE = 'M001';
SELECT * FROM MAKER2;
SELECT * FROM PRODUCT22;

UPDATE MAKER2 SET MAKER_CODE = 'M003' WHERE MAKER_CODE = 'M002';
