DROP TABLE MAKER2, PRODUCT22;
CREATE TABLE MAKER2(MAKER_CODE CHAR(4) PRIMARY KEY, MAKER_NAME VARCHAR(30));
CREATE TABLE PRODUCT22(PRODUCT_CODE CHAR(4) PRIMARY KEY, PRODUCT_NAME VARCHAR(30), MAKER_CODE CHAR(4),
FOREIGN KEY (MAKER_CODE) REFERENCES MAKER2(MAKER_CODE) ON DELETE CASCADE ON UPDATE CASCADE);

INSERT INTO MAKER2 VALUES('M001', '나이키');
INSERT INTO MAKER2 VALUES('M002', '리복');

INSERT INTO PRODUCT22 VALUES('P001', '축구화', 'M001');
INSERT INTO PRODUCT22 VALUES('P002', '러닝화', 'M002');

DELETE FROM MAKER2 WHERE MAKER_CODE = 'M001';
UPDATE MAKER2 SET MAKER_CODE = 'M003' WHERE MAKER_CODE = 'M002';

SELECT * FROM MAKER2;
SELECT * FROM PRODUCT22;

SHOW DATABASES;

DESC INFORMATION_SCHEMA.TABLE_CONSTRAINTS;

SELECT CONSTRAINT_NAME, TABLE_NAME, CONSTRAINT_TYPE FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'PRODUCT22';

ALTER TABLE PRODUCT22 ADD CONSTRAINT PRODUCT22_MAKERCODE_FK FOREIGN KEY (MAKER_CODE) REFERENCES MAKER2(MAKER_CODE) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PRODUCT22 DROP primary key;
ALTER TABLE PRODUCT22 ADD CONSTRAINT PK PRIMARY KEY(PRODUCT_CODE); -- 프라이머리 키는 이름 못 지음. 무조건 하나이기 때문. 이름 겹칠 일이 없기 때문에 이름 짓지 않음.