CREATE DATABASE p20230913;
USE P20230913;

CREATE TABLE A(NO INT);
INSERT INTO A VALUES(1);
INSERT INTO A VALUES(2);
INSERT INTO A VALUES(3);

CREATE TABLE B(NO INT);
INSERT INTO B VALUES(2);
INSERT INTO B VALUES(10);
INSERT INTO B VALUES(11);

SELECT * FROM A;
SELECT * FROM B;

SELECT * FROM A UNION SELECT * FROM B;
SELECT NO FROM A WHERE A.NO NOT IN (SELECT NO FROM B);
SELECT NO FROM A WHERE A.NO IN (SELECT NO FROM B);

SELECT A.no, B.NO FROM A LEFT JOIN B on A.no = B.no ;
SELECT * FROM A EXCEPT SELECT * FROM B;
SELECT * FROM A INTERSECT SELECT * FROM B;

