USE P20230912;
CREATE TABLE SAMPLE62(NO INT, A VARCHAR(10));

INSERT INTO SAMPLE62 VALUES(2, 'ABC');
INSERT INTO SAMPLE62 VALUES(1, 'DEF');
INSERT INTO SAMPLE62 VALUES(100, 'GHI');
INSERT INTO SAMPLE62 VALUES(3, 'JKL');
INSERT INTO SAMPLE62 VALUES(101, 'MNO');

CREATE INDEX ISAMPLE62 ON SAMPLE62(NO);

SHOW INDEX FROM SAMPLE62;

DROP INDEX ISAMPLE62 ON SAMPLE62;
CREATE INDEX ISAMPLE62 ON SAMPLE62(A);

SELECT * FROM SAMPLE62 WHERE A = 'A';
EXPLAIN (SELECT * FROM SAMPLE62 WHERE A = 'A');

EXPLAIN(SELECT * FROM SAMPLE62 WHERE no > 10);

