USE P20230912;
DROP TABLE SAMPLE54;
CREATE TABLE SAMPLE54 (NO INT AUTO_INCREMENT PRIMARY KEY, A INT);
INSERT INTO SAMPLE54(A) VALUES(100);
INSERT INTO SAMPLE54(A) VALUES(80);
INSERT INTO SAMPLE54(A) VALUES(40);
INSERT INTO SAMPLE54(A) VALUES(20);
INSERT INTO SAMPLE54(A) VALUES(10);

DROP VIEW SAMPLE_VIEW_54;
CREATE VIEW SAMPLE_VIEW_54 AS SELECT * FROM SAMPLE54;
SELECT * FROM SAMPLE_VIEW_54;
DROP VIEW SAMPLE_VIEW_541;
CREATE VIEW SAMPLE_VIEW_541 AS SELECT NO 'N', A V, A*2 V2 FROM SAMPLE54;
ALTER TABLE SAMPLE54 ADD K INT;
-- UPDATE SAMPLE54 SET K = (SELECT V2 FROM SAMPLE_VIEW_541 WHERE NO = N); -- K와 V2의 행 수가 같음을 보장할 수 없음
SELECT * FROM SAMPLE54;
SELECT * FROM SAMPLE_VIEW_541;
SELECT * FROM SAMPLE_VIEW_541 WHERE N = 1;
CREATE VIEW SAMPLE_VIEW_542 AS SELECT NO, A FROM SAMPLE54;
SELECT * FROM SAMPLE_VIEW_542;
DROP VIEW SAMPLE_VIEW_54;
